# Generated by Django 5.1.4 on 2024-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_video", models.FileField(upload_to="videos/")),
                (
                    "processed_video",
                    models.FileField(
                        blank=True, null=True, upload_to="processed_videos/"
                    ),
                ),
            ],
        ),
    ]
