# Generated by Django 5.1.4 on 2024-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="processed_video",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
